INSERT INTO roles(role) values('user'),('lawyer'),('admin');

INSERT INTO specializations(name) values
('Agrarrecht'),
('Allgemeines Vertragsrecht'),
('Anwaltshaftung'),
('Arbeitsrecht'),
('Arzthaftungsrecht'),
('Ausländerrecht & Asylrecht'),
('Bankrecht & Kapitalmarktrecht'),
('Baurecht & Architektenrecht'),
('Beamtenrecht'),
('Betreuungsrecht'),
('Betriebliche Altersversorgung'),
('Datenschutzrecht'),
('Designrecht'),
('Erbrecht'),
('Familienrecht'),
('Forderungseinzug & Inkassorecht'),
('Gewerblicher Rechtsschutz'),
('Grundstücksrechts & Immobilienrecht'),
('Insolvenzrecht'),
('Internationales Recht'),
('Internationales Wirtschaftsrecht'),
('IT-Recht'),
('Jagdrecht'),
('Kaufrecht'),
('Maklerrecht'),
('Markenrecht'),
('Mediation'),
('Medizinrecht'),
('Mietrechts & Wohnungseigenturmsrecht'),
('Migrationsrecht'),
('Öffentliches Baurecht'),
('Öffentliches Rechts'),
('Opferhilfe'),
('Ordnungswidrigkeitenrecht'),
('Patentrecht'),
('Pferderecht'),
('Pflegerecht'),
('Rechts rund ums Tier'),
('Reiserecht'),
('Schadensersatzrecht &'),
('Schmerzensgeldrecht'),
('Schiedsgerichtsbarkeit'),
('Secht'),
('Schwerbehindertenrecht'),
('Sozialrecht'),
('Sozialversicherungsrecht'),
('Sportrecht'),
('Steuerrecht'),
('StrafrechtAgrarrecht'),
('Allgemeines Vertragsrecht'),
('Anwaltshaftung'),
('Arzthaftungsrecht'),
('Ausländerrecht & Asylrecht'),
('Bankrecht & Kapitalmarktrecht'),
('Baurecht & Architektenrecht'),
('Betreuungsrecht'),
('Betriebliche Altersversorgung'),
('Datenschutzrecht'),
('Designrecht'),
('Erbrecht'),
('Familienrecht'),
('Forderungseinzug & Inkassorecht'),
('Gewerblicher Rechtsschutz'),
('Grundstücksrechts & Immobilienrecht'),
('Insolvenzrecht'),
('Internationales Recht'),
('Internationales Wirtschaftsrecht'),
('IT-Recht'),
('Jagdrecht'),
('Kaufrecht'),
('Maklerrecht'),
('Markenrecht'),
('Mediation'),
('Medizinrecht'),
('Mietrechts & Wohnungseigenturmsrecht'),
('Migrationsrecht'),
('Öffentliches Baurecht'),
('Öffentliches Rechts'),
('Opferhilfe'),
('Ordnungswidrigkeitenrecht'),
('Patentrecht'),
('Pferderecht'),
('Pflegerecht'),
('Rechts rund ums Tier'),
('Reiserecht'),
('Schadensersatzrecht &'),
('Schmerzensgeldrecht'),
('Schiedsgerichtsbarkeit'),
('Secht'),
('Schwerbehindertenrecht'),
('Sozialrecht'),
('Sozialversicherungsrecht'),
('Sportrecht'),
('Steuerrecht'),
('Strafrecht'),
('Transportrecht & Speditionsrecht'),
('Umweltrecht'),
('Unterhaltsrecht'),
('Unternehmensrecht & Betriebsnachfolge'),
('Urheberrecht & Medienrecht'),
('Vereinsrecht & Verbandsrecht'),
('Verfassungsrecht'),
('Vergaberecht'),
('Verkehrsrecht'),
('Versicherungsrecht'),
('Verwaltungsrecht'),
('Werkvertragsrecht'),
('Wettbewerbsrecht'),
('Wirtschaftsrecht'),
('Zivilprozessrecht'),
('Zivilrecht'),
('Zwangsvollstreckungsrecht'),
('Erbrecht'),
('Familienrecht'),
('Handelsrecht & Gesellschaftsrecht'),
('Immobilienrecht'),
('Vorsorgevollmacten'),
('Sonstige Beglaubigungen & Beurkundung');


INSERT INTO languages(language) values
('Arabisch'),
('Englisch'),
('Französisch'),
('Gebärdensprache'),
('Italienisch'),
('Persisch'),
('Polnisch'),
('Portugiesisch'),
('Rumänisch'),
('Russisch'),
('Spanisch'),
('Türkisc');

INSERT INTO week_days(name) values
('Sunday'),
('Monday'),
('Tuesday'),
('Wednesday'),
('Thursday'),
('Friday'),
('Saturday');

        INSERT INTO time_slots(time_range) VALUES
        ('9:00, 9:15'),
        ('9:15, 9:30'),
        ('9:30, 9:45'),
        ('9:45, 10:00'),
        ('10:00, 10:15'),
        ('10:15, 10:30'),
        ('10:30, 10:45'),
        ('10:45, 11:00'),
        ('11:00, 11:15'),
        ('11:15, 11:30'),
        ('11:30, 11:45'),
        ('11:45, 12:00'),
        ('12:00, 12:15'),
        ('12:15, 12:30'),
        ('12:30, 12:45'),
        ('12:45, 13:00'),
        ('13:00, 13:15'),
        ('13:15, 13:30'),
        ('13:30, 13:45'),
        ('13:45, 14:00'),
        ('14:00, 14:15'),
        ('14:15, 14:30'),
        ('14:30, 14:45'),
        ('14:45, 15:00'),
        ('15:00, 15:15'),
        ('15:15, 15:30'),
        ('15:30, 15:45'),
        ('15:45, 16:00'),
        ('16:00, 16:15'),
        ('16:15, 16:30'),
        ('16:30, 16:45'),
        ('16:45, 17:00'),
        ('17:00, 17:15'),
        ('17:15, 17:30'),
        ('17:30, 17:45'),
        ('17:45, 18:00'),
        ('18:00, 18:15'),
        ('18:15, 18:30'),
        ('18:30, 18:45'),
        ('18:45, 19:00'),
        ('19:00, 19:15'),
        ('19:15, 19:30'),
        ('19:30, 19:45'),
        ('19:450:00'),
        ('20:000:15'),
        ('20:150:30'),
        ('20:300:45'),
        ('20:451:00'),
        ('21:001:15'),
        ('21:151:30'),
        ('21:301:45'),
        ('21:452:00');
        
